name: BuildandDeploytoStaging
on:
push:
    branches:
      -main
    tags:
      -'*'
jobs:
build:
    name:Buildnodejsproject
    runs-on:ubuntu-latest
    steps:
      -name:CheckoutCode
        uses:actions/checkout@v3
      -name:SetupNode.js
        uses:actions/setup-node@v3
        with:
          node-version:'20.8.1'
      -name:InstallDependencies
        run:npminstall
      -name:BuildReactApp
        run:npmrunbuild
docker:
    name:DockerBuildandPush
    runs-on:ubuntu-latest
    needs:build
    steps:
      -name:CheckoutCode
        uses:actions/checkout@v3
      -name:LogintoDockerHub
        uses:docker/login-action@v2
        with:
          username:${{secrets.DOCKER_USERNAME}}
          password:${{secrets.DOCKER_PASSWORD}}
      -name:BuildDockerImage
        run:|
          docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-test:latest .
      -name:PushDockerImage
        run:|
          docker push ${{ secrets.DOCKER_USERNAME }}/github-action-test:latest
deploy:
    name:DeploytoRemoteVPS
    runs-on:ubuntu-latest
    needs:docker
    steps:
      -name:DeployviaSSH
        uses:appleboy/ssh-action@v1.2.0
        with:
          host:${{secrets.REMOTE_HOST}}
          username:${{secrets.REMOTE_USER}}
          password:${{secrets.SSH_PRIVATE_KEY}}
          script: |
            echo "Navigating to the Docker Compose file directory"
            cd /path to your repo/ 
            echo "Stopping and removing any running containers"
            docker stop <container name>
            docker rm <container name>
            echo "Removing the old Docker image"
            docker rmi -f <latest image>|| true
            echo "Logging into Docker Hub on the remote server"
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "Pulling the latest image"
            docker compose up --build -d
