#Author：Eiwen
#Date： 2024/04/16
 
name: 阿飞的workflow
 
on: push
 
jobs:
  my-job:
    name: 测试任务
    runs-on: ubuntu-latest
    steps:
      - name: 打印文本
        run: |
          echo 我的名字是阿飞
      #- name: 下载源码文件
        #uses: actions/checkout@master 
      #- name: 上传文件到服务器
       # uses: appleboy/scp-action@v0.1.7
       # with:
          #host: ${{ secrets.HOST }}
          #username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
          #port: ${{ secrets.PORT }}
          #source: "*"
          #target: "./website/eiwen-disk"
      - name: 执行远程SSH命令
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: | 
            cd website/eiwen-disk
            npm i
            npm i pm2 -g
            pm2 reload bin/www --name disk
      

